Update snyk_code.yml

diff --git a/.github/workflows/snyk_code.yml b/.github/workflows/snyk_code.yml
--- a/.github/workflows/snyk_code.yml
+++ b/.github/workflows/snyk_code.yml
@@ -27,7 +27,14 @@ jobs:
     - name: confirm json
       run: cat results-code.json
     - name: snyk-to-html
-      run: snyk-to-html -i results-code.json -o results-code.html --debug
+      run: snyk-to-html -i results-code.json -o results-code.html
+    - name: test snyk-to-html
+      run:  if command -v snyk-to-html &> /dev/null; then
+                   snyk-to-html -i results-code.json -o results-code.html --debug
+               else
+                  echo "snyk-to-html not found"
+                  exit 1
+              fi
     - name: Upload html output
       uses: actions/upload-artifact@v4.6.1
       with:
