Update snyk_code.yml

diff --git a/.github/workflows/snyk_code.yml b/.github/workflows/snyk_code.yml
--- a/.github/workflows/snyk_code.yml
+++ b/.github/workflows/snyk_code.yml
@@ -20,18 +20,16 @@ jobs:
       run: |
          sudo npm install -g snyk-to-html
     - name: Snyk code test
-      run: snyk code test --json-file-output=./results-code.json
+      run: snyk code test --json-file-output=results-code.json
       env:
         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       continue-on-error: true
     - name: confirm json
-      run: cat ./results-code.json
+      run: cat results-code.json
     - name: test snyk-to-html
-      run:  if command -v snyk-to-html &> /dev/null; then snyk-to-html -i ./results-code.json -o ./results-code.html --debug; else echo "snyk-to-html not found"; exit 1; fi
-    - name: cat ./results-code.html
-      run: cat ./results-code.html
+      run:  if command -v snyk-to-html &> /dev/null; then snyk-to-html -i $(pwd)/results-code.json -o results-code.html --debug; else echo "snyk-to-html not found"; exit 1; fi
     - name: Upload html output
       uses: actions/upload-artifact@v4.6.1
       with:
        name: results-code.html
-       path: ./results-code.html
+       path: results-code.html
